# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install deps, build, prune dev dependencies
RUN npm install && npm run build && npm prune --production

# Default command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]
